In [ ]:
#read csv
import pandas as pd

df = pd.read_csv('Datasets/data.csv',usecols=['Pulse','Maxpulse'])
df.head()

   Pulse  Maxpulse
0    110       130
1    117       145
2    103       135
3    109       175
4    117       148

In [12]:
#opeaning csv file from url
import pandas as pd 
import requests
from io import StringIO

url ="https://raw.githubusercontent.com/campusx-official/placement-project-logistic-regression/refs/heads/main/placement.csv"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"}
response = requests.get(url, headers=headers)
data = StringIO(response.text)

pd.read_csv(data, names=['sno', 'cgpa', 'iq', 'placement'], sep=",", index_col='sno', header=1)

     cgpa     iq  placement
sno
1     5.9  106.0          0
2     5.3  121.0          0
3     7.4  132.0          1
4     5.8  142.0          0
5     7.1   48.0          1
..    ...    ...        ...
95    4.3  200.0          0
96    4.4   42.0          0
97    6.7  182.0          1
98    6.3  103.0          1
99    6.2  113.0          1

[99 rows x 3 columns]

In [9]:
pd.read_csv('Datasets/placement.csv', usecols=['cgpa', 'iq'])

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [ ]:
pd.read_csv('Datasets/placement.csv', nrows=10) # 10 rows are read from the top

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0
5           5   7.1   48.0          1
6           6   5.7  143.0          0
7           7   5.0   63.0          0
8           8   6.1  156.0          0
9           9   5.1   66.0          0

In [4]:
url="https://raw.githubusercontent.com/solidsnack/tsv/refs/heads/master/cities10.tsv"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"}
response = requests.get(url, headers=headers)
data = StringIO(response.text)

pd.read_csv(data, sep="\t")

   AC               Acrelândia  12538  1807.92
0  AL             Boca da Mata  25776   186.53
1  AL                   Capela  17077   242.62
2  AP          Tartarugalzinho  12563  6709.66
3  BA          América Dourada     \N   837.72
4  CE   Jijoca de Jericoacoara  17002   204.79
5  GO               Cavalcante   9392  6953.67
6  MA  Centro Novo do Maranhão  17622  8258.42
7  MS          Ped\\ro G\\omes   7967  3651.18
8  MG      Abadia dos Dourados   6704   881.06

In [ ]:
'''
| Encoding | Use case                          |
| -------- | --------------------------------- |
| `utf-8`  | Most common, works for most files |
| `latin1` | Western European languages        |
| `cp1252` | Windows-based files               |
'''
#we will use encoding parameter while reading the file
#it will not give error :UnicodeDecodeError
pd.read_csv('Datasets/encodeingtest.csv', encoding='latin1')


#error bad lines
#it will skip bad lines "error_bad_lines"

    name
0  JosÃ©
1  CafÃ©

In [17]:
df = pd.read_csv("Datasets/data3.csv", dtype={
    "id": str,
    "age": int,
    "score": float
})

print(df)
print(df.dtypes)

    id   name  age  score
0  001   John   21   85.5
1  002  Alice   22   90.0
2  003    Bob   20   88.0
id        object
name      object
age        int64
score    float64
dtype: object

In [23]:
#loading a huge data set in chunks

dfs = pd.read_csv('Datasets/BMW sales data (2010-2024) (1).csv', chunksize= 5000)

for chunk in dfs:
    print(chunk.shape)

(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)
(5000, 11)

In [3]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

pd.read_sql("SELECT * FROM city", conn)

C:\Users\ravjot\AppData\Local\Temp\ipykernel_27168\1587041457.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FROM city", conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [4]:
pd.read_sql("SELECT * FrOM city WHERE CountryCode = 'IND'", conn)

C:\Users\ravjot\AppData\Local\Temp\ipykernel_27168\1582674627.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FrOM city WHERE CountryCode = 'IND'", conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [ ]:
#fetching data from API
import pandas as pd