In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('Datasets/covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()   #there are missing values in fever will impute them :)

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2, random_state=2)

In [ ]:
X_train.head() #will apply ordinal on 'cough' amd onehot on 'gender'and 'city' and impute on 'fever'

    age  gender  fever   cough       city
35   82  Female  102.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
84   69  Female   98.0  Strong     Mumbai
44   20    Male  102.0  Strong      Delhi
73   34    Male   98.0  Strong    Kolkata

In [7]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('t1', SimpleImputer(),['fever']),
    ('t2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('t3', OneHotEncoder(sparse_output=False, drop='first'),['gender','city'])
],remainder='passthrough')# remainder will keep the other columns as it is or drop them if we set remainder='drop'

In [9]:
transformer.fit_transform(X_train).shape

(80, 7)

In [10]:
transformer.fit_transform(X_train).shape

(80, 7)